name: Dependency Review
permissions: {}
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Harden Runner
        if: false
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.deps.dev:443
            api.github.com:443
            github.com:443
      - name: Checkout
        uses: actions/checkout@main # v4.2.2
        with:
          persist-credentials: false
      - name: Dependency Review
        uses: jsoref/dependency-review-action@issue-919
        with:
          license-check: false
          comment-summary-in-pr: on-failure
          retry-on-snapshot-warnings: true
          retry-on-snapshot-warnings-timeout: 600
